##################################################################################################
# year-go instrumentation
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: year-go
  labels:
    app: year-go
    app.kubernetes.io/name: year-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: year-go-svc
  template:
    metadata:
      labels:
        app: year-go-svc
    spec:
      shareProcessNamespace: true
      securityContext: {}
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: copy-launcher
        image: keyval/launcher:v0.1
        imagePullPolicy: IfNotPresent
        command:
          - cp
          - -a
          - /kv-launcher/.
          - /launcher/
        volumeMounts:
          - name: launcherdir
            mountPath: /launcher
      containers:
        - name: year-go-svc
          image: year-go-auto:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6001
          command:
            - /launcher/launch
            - /app/year-service
          volumeMounts:
            - mountPath: /launcher
              name: launcherdir
        - name: year-go-instrumentation
          image: keyval/otel-go-agent:v0.6.4
          imagePullPolicy: IfNotPresent
          env:
          - name: OTEL_TARGET_EXE
            value: /app/year-service
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: otel-collector:4317
          - name: OTEL_SERVICE_NAME
            value: year-go-auto
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
          volumeMounts:
          - mountPath: /sys/kernel/debug
            name: kernel-debug
      volumes:
      - name: launcherdir
        emptyDir: {}
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
