##################################################################################################
# year-go services
##################################################################################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: year-go
---
apiVersion: v1
kind: Service
metadata:
  name: year-go-svc
  labels:
    app: year-go-svc
    service: year-go-svc
    app.kubernetes.io/name: year-go
spec:
  selector:
    app: year-go-svc
  ports:
  - name: http
    port: 6001
    targetPort: 6001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: year-go
  labels:
    app: year-go
    app.kubernetes.io/name: year-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: year-go-svc
  template:
    metadata:
      labels:
        app: year-go-svc
    spec:
      serviceAccountName: year-go
      terminationGracePeriodSeconds: 0
      containers:
      - env:
        name: year-go-svc
        image: year-go-auto:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6001
          name: http
        resources:
          requests:
            cpu: 100m
---
