version: "2.4"

services:
  frontend:
    build:
        context: .
        dockerfile: ./frontend-service/Dockerfile
    image: egs-frontend-go
    ports:
      - 7777:7777

  message:
    build:
        context: .
        dockerfile: ./message-service/Dockerfile
    image: egs-message-go
    ports:
      - 9000:9000

  name:
    build:
        context: .
        dockerfile: ./name-service/Dockerfile
    image: egs-name-go
    ports:
      - 8000:8000

  year:
    build:
        context: .
        dockerfile: ./year-service/Dockerfile
    image: egs-year-go
    ports:
      - 6001:6001

