version: "2.4"

services:
  frontend:
    build:
        context: .
        dockerfile: ./frontend/Dockerfile
    image: hnyexample/frontend-go-uninstrumented
    ports:
      - 7777:7777

  message:
    build:
        context: .
        dockerfile: ./message-service/Dockerfile
    image: hnyexample/message-go-uninstrumented
    ports:
      - 9000:9000

  name:
    build:
        context: .
        dockerfile: ./name-service/Dockerfile
    image: hnyexample/name-go-uninstrumented
    ports:
      - 8000:8000

  year:
    build:
        context: .
        dockerfile: ./year-service/Dockerfile
    image: hnyexample/year-go-uninstrumented
    ports:
      - 6001:6001

