version: "2.4"

x-common-env: &common-env
  HONEYCOMB_API_KEY:
  HONEYCOMB_DATASET:
  HONEYCOMB_API:
  OTEL_EXPORTER_OTLP_ENDPOINT:
  OTEL_EXPORTER_OTLP_HEADERS:
  OTEL_RESOURCE_ATTRIBUTES: app.running-in=docker
  MESSAGE_ENDPOINT: http://message:9000
  NAME_ENDPOINT: http://name:8000
  YEAR_ENDPOINT: http://year:6001
  REDIS_URL: redis

services:
  frontend:
    build: ./frontend
    image: hnyexample/frontend-ruby
    environment:
      <<: *common-env
    ports:
      - 7777:7777

  message:
    build: ./message-service
    image: hnyexample/message-ruby
    environment:
      <<: *common-env
    ports:
      - 9000:9000

  name:
    build: ./name-service
    image: hnyexample/name-ruby
    environment:
      <<: *common-env
    ports:
      - 8000:8000

  year:
    build: ./year-service
    image: hnyexample/year-ruby
    environment:
      <<: *common-env
    ports:
      - 6001:6001

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"