apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  labels:
    app: collector
spec:
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: otel/opentelemetry-collector-dev
        # command: ["--config=/etc/otel/config.yaml"]
        volumeMounts:
        - name: config-file
          mountPath: /etc/otel
          readOnly: true
        ports:
        - containerPort: 55680
        - containerPort: 55681
        env:
          - name: HONEYCOMB_API_ENDPOINT
            value: api.honeycomb.io:443
          - name: HONEYCOMB_API_KEY
            valueFrom:
              configMapKeyRef:
                name: hny-config
                key: api_key
          - name: HONEYCOMB_DATASET
            valueFrom:
              configMapKeyRef:
                name: hny-config
                key: dataset
      volumes:
      - name: config-file
        configMap:
          name: collector-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
        loglevel: debug
      otlp/hny:
        endpoint: "${HONEYCOMB_API_ENDPOINT}"
        headers:
          "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
          "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp/hny, logging]
