apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  selector:
    app: collector
  ports:
    - name: otlp-grpc
      port: 55680
      targetPort: 55680
      protocol: TCP
    - name: otlp-http
      port: 55681
      targetPort: 55681
      protocol: TCP
