apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        # zipkin for b3 propagation
        # zipkin:
        #   address: otel-collector.default:9411
        # openCensusAgent for w3c propagation
        # openCensusAgent:
        #     address: otel-collector.default:55678
        # sampling: 100
    extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-collector.otel-collector.svc.cluster.local
    defaultProviders:
      tracing:
        - otel-tracing
---