apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        custom_tags:
          is_it_istio:
            literal:
              value: yep
        zipkin:
          address: otel-collector.default:9411
        sampling: 100
---