# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
# DOTNET
  - package-ecosystem: "nuget"
    directory: "/dotnet"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
# ELIXIR
  - package-ecosystem: "mix"
    directory: "/elixir/frontend"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "mix"
    directory: "/elixir/message"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "mix"
    directory: "/elixir/name"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "mix"
    directory: "/elixir/year"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
# GOLANG
  - package-ecosystem: "gomod"
    directory: "/golang/frontend"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "gomod"
    directory: "/golang/message-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "gomod"
    directory: "/golang/name-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "gomod"
    directory: "/golang/year-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
# JAVA
  - package-ecosystem: "gradle"
    directory: "/java/frontend"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "gradle"
    directory: "/java/message-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "gradle"
    directory: "/java/name-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "gradle"
    directory: "/java/year-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
# NODE
  - package-ecosystem: "npm"
    directory: "/node/frontend"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "npm"
    directory: "/node/message-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "npm"
    directory: "/node/name-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "npm"
    directory: "/node/year-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
# PYTHON
  - package-ecosystem: "pip"
    directory: "/python/frontend"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "pip"
    directory: "/python/message-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "pip"
    directory: "/python/name-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "pip"
    directory: "/python/year-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
# RUBY
  - package-ecosystem: "bundler"
    directory: "/ruby/frontend"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "bundler"
    directory: "/ruby/message-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "bundler"
    directory: "/ruby/name-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
  - package-ecosystem: "bundler"
    directory: "/ruby/year-service"
    schedule:
        interval: "monthly"
    labels:
        - "type: dependencies"
    reviewers:
        - "honeycombio/telemetry-team"
