# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
# DOTNET
  - package-ecosystem: "nuget"
    directory: "/dotnet"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
# ELIXIR
  - package-ecosystem: "mix"
    directory: "/elixir/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "mix"
    directory: "/elixir/message"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "mix"
    directory: "/elixir/name"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "mix"
    directory: "/elixir/year"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
# GOLANG
  - package-ecosystem: "gomod"
    directory: "/golang"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
# JAVA
  - package-ecosystem: "gradle"
    directory: "/java/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "gradle"
    directory: "/java/message-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "gradle"
    directory: "/java/name-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "gradle"
    directory: "/java/year-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
# NODE
  - package-ecosystem: "npm"
    directory: "/node/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/node/message-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/node/name-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/node/year-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
# PYTHON
  - package-ecosystem: "pip"
    directory: "/python/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "/python/message-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "/python/name-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "/python/year-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
# RUBY
  - package-ecosystem: "bundler"
    directory: "/ruby/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "bundler"
    directory: "/ruby/message-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "bundler"
    directory: "/ruby/name-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
  - package-ecosystem: "bundler"
    directory: "/ruby/year-service"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
# WEB
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
    reviewers:
      - "honeycombio/pipeline-team"
    commit-message:
      prefix: "maint"
      include: "scope"
