version: "2.4"

# noinspection ComposeUnknownKeys
x-common-env: &common-env
  HONEYCOMB_API_KEY:
  HONEYCOMB_DATASET:
  HONEYCOMB_API:
  OTEL_EXPORTER_OTLP_ENDPOINT:
  OTEL_EXPORTER_OTLP_HEADERS:
  OTEL_RESOURCE_ATTRIBUTES: app.running-in=docker
  Honeycomb__ApiKey: ${HONEYCOMB_API_KEY}
  Honeycomb__Dataset: ${HONEYCOMB_DATASET}
  Honeycomb__Endpoint: ${HONEYCOMB_API}
  Otlp__ApiKey: ${HONEYCOMB_API_KEY}
  Otlp__Dataset: ${HONEYCOMB_DATASET}
  Otlp__Endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
  MESSAGE_ENDPOINT: message-service:9000
  NAME_ENDPOINT: name-service:8000
  YEAR_ENDPOINT: year-service:6001
  REDIS_URL: redis

services:
  frontend-dotnet:
    container_name: frontend-service
    build: ./dotnet/frontend
    image: hnyexample/frontend-dotnet
    environment:
      <<: *common-env
    ports:
      - 7777:7777

  message-dotnet:
    container_name: message-service
    build: ./dotnet/message-service
    image: hnyexample/message-dotnet
    environment:
      <<: *common-env
    ports:
      - 9000:9000

  name-dotnet:
    container_name: name-service
    build: ./dotnet/name-service
    image: hnyexample/name-dotnet
    environment:
      <<: *common-env
    ports:
      - 8000:8000

  year-dotnet:
    container_name: year-service
    build: ./dotnet/year-service
    image: hnyexample/year-dotnet
    environment:
      <<: *common-env
    ports:
      - 6001:6001
