version: "2.4"

# noinspection ComposeUnknownKeys
x-common-env: &common-env
    HONEYCOMB_API_KEY:
    HONEYCOMB_DATASET:
    HONEYCOMB_API:
    OTEL_EXPORTER_OTLP_ENDPOINT:
    OTEL_EXPORTER_OTLP_HEADERS:
    OTEL_RESOURCE_ATTRIBUTES: app.running-in=docker
    MESSAGE_ENDPOINT: http://message-python:9000
    NAME_ENDPOINT: http://name-python:8000
    YEAR_ENDPOINT: http://year-python:6001

services:
  frontend-python:
    build: ./python/frontend
    image: hnyexample/frontend-python
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: frontend-python
    ports:
      - 7777:7777

  message-python:
    build: ./python/message-service
    image: hnyexample/message-python
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: message-python
    ports:
      - 9000:9000

  name-python:
    build: ./python/name-service
    image: hnyexample/name-python
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: name-python
    ports:
      - 8000:8000

  year-python:
    build: ./python/year-service
    image: hnyexample/year-python
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: year-python
    ports:
      - 6001:6001

