##################################################################################################
# year-go services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: year-go
  labels:
    app: year-go
    service: year-go
spec:
  ports:
    - port: 6001
      name: http
  selector:
    app: year-go
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: year-go
  labels:
    account: year-go
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: year-go
  labels:
    app: year-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: year-go
  template:
    metadata:
      labels:
        app: year-go
    spec:
      serviceAccountName: year-go
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 0
      initContainers:
        - name: copy-launcher
          image: keyval/launcher:v0.1
          command:
            - cp
            - -a
            - /kv-launcher/.
            - /odigos-launcher/
          volumeMounts:
          - name: launcherdir
            mountPath: /odigos-launcher

      containers:
        - name: year-go
          image: year-go:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6001
          env:
            - name: OTEL_SERVICE_NAME
              value: year-go
            - name: DEBUG
              value: "true"
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: honeycomb
          command:
            - /odigos-launcher/launch
            - /app/year-service
          volumeMounts:
             - name: launcherdir
               mountPath: /odigos-launcher
          resources:
            requests:
              cpu: 100m
        - name: year-go-auto-instrumentation
          image: keyval/otel-go-agent:v0.6.0
          env:
            - name: OTEL_TARGET_EXE
              value: /app/year-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "api.honeycomb.io:443"
            - name: OTEL_SERVICE_NAME
              value: year-go-auto
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: honeycomb
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: "x-honeycomb-team=$HONEYCOMB_API_KEY"
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: kernel-debug
      volumes:
        - name: launcherdir
          emptyDir: {}
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
---
