opentelemetry_config /etc/otel-conf.toml;

upstream frontend {
	server frontend-dotnet:7000;
	server frontend-go:7000;
	server frontend-java:7000;
	server frontend-python:7000;
	server frontend-ruby:7000;
}

upstream message {
	server message-go:9000;
	server message-java:9000;
	server message-python:9000;
	server message-ruby:9000;
}

upstream name {
	server name-dotnet:8000;
	server name-go:8000;
	server name-java:8000;
	server name-python:8000;
	server name-ruby:8000;
}

upstream year {
	server year-dotnet:6001;
	server year-go:6001;
	server year-java:6001;
	server year-python:6001;
	server year-ruby:6001;
}

server {
	listen 80 default_server;
	server_name _;

	location / {
		opentelemetry_operation_name catch_all;
		root /usr/share/nginx/html;
		try_files $uri /index.html;
	}

	location /greeting {
		access_log /dev/stdout upstreamlog;

		opentelemetry_operation_name frontend_proxy;
		opentelemetry_attribute "upstream" "$upstream_addr";
    opentelemetry_propagate;

		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-NginX-Proxy true;
		proxy_pass http://frontend;
		proxy_ssl_session_reuse off;
		proxy_set_header Host $http_host;
		proxy_cache_bypass $http_upgrade;
		proxy_redirect off;
	}

	location /message {
		access_log /dev/stdout upstreamlog;

		opentelemetry_operation_name message_proxy;
		opentelemetry_attribute "upstream" "$upstream_addr";
    opentelemetry_propagate;

		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-NginX-Proxy true;
		proxy_pass http://message;
		proxy_ssl_session_reuse off;
		proxy_set_header Host $http_host;
		proxy_cache_bypass $http_upgrade;
		proxy_redirect off;
	}

	location /name {
		access_log /dev/stdout upstreamlog;

		opentelemetry_operation_name name_proxy;
		opentelemetry_attribute "upstream" "$upstream_addr";
    opentelemetry_propagate;

		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-NginX-Proxy true;
		proxy_pass http://name;
		proxy_ssl_session_reuse off;
		proxy_set_header Host $http_host;
		proxy_cache_bypass $http_upgrade;
		proxy_redirect off;
	}

	location /year {
		access_log /dev/stdout upstreamlog;

		opentelemetry_operation_name year_proxy;
		opentelemetry_attribute "upstream" "$upstream_addr";
    opentelemetry_propagate;

		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-NginX-Proxy true;
		proxy_pass http://year;
		proxy_ssl_session_reuse off;
		proxy_set_header Host $http_host;
		proxy_cache_bypass $http_upgrade;
		proxy_redirect off;
	}
}
