apiVersion: apps/v1
kind: Deployment
metadata:
  name: year-ruby
  labels:
    app: year
    language: ruby
spec:
  selector:
    matchLabels:
      app: year
      language: ruby
  template:
    metadata:
      labels:
        app: year
        language: ruby
    spec:
      containers:
      - name: year-ruby
        image: hnyexample/year-ruby
        ports:
        - containerPort: 6001
        env:
        - name: HONEYCOMB_API_KEY
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: api_key
        - name: HONEYCOMB_DATASET
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: dataset
        - name: SERVICE_NAME
          value: year-ruby

---
apiVersion: v1
kind: Service
metadata:
  name: year-ruby
spec:
  selector:
    app: year
    language: ruby
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
