apiVersion: apps/v1
kind: Deployment
metadata:
  name: year-java
  labels:
    app: year
spec:
  selector:
    matchLabels:
      app: year
  template:
    metadata:
      labels:
        app: year
    spec:
      containers:
      - name: year-java
        image: hnyexample/year-java
        ports:
        - containerPort: 6001
        env:
        - name: HONEYCOMB_API_KEY
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: api_key
        - name: HONEYCOMB_DATASET
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: dataset
        - name: SERVICE_NAME
          value: year-java
