##################################################################################################
# message-go services
##################################################################################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: message-go
---
apiVersion: v1
kind: Service
metadata:
  name: message-go-svc
  labels:
    app: message-go-svc
    service: message-go-svc
    app.kubernetes.io/name: message-go
spec:
  selector:
    app: message-go-svc
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-go
  labels:
    app: message-go
    app.kubernetes.io/name: message-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-go-svc
  template:
    metadata:
      labels:
        app: message-go-svc
    spec:
      serviceAccountName: message-go
      terminationGracePeriodSeconds: 0
      containers:
      - env:
        name: message-go-svc
        image: message-go-auto:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: http
        resources:
          requests:
            cpu: 100m
---
