apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dotnet
  labels:
    app: frontend
    language: dotnet
spec:
  selector:
    matchLabels:
      app: frontend
      language: dotnet
  template:
    metadata:
      labels:
        app: frontend
        language: dotnet
    spec:
      containers:
      - name: frontend-dotnet
        image: hnyexample/frontend-dotnet
        ports:
        - containerPort: 7000
        env:
          - name: Otlp__Endpoint
            value: "http://collector:55680"
          - name: NAME_ENDPOINT
            value: http://gateway
          - name: MESSAGE_ENDPOINT
            value: http://gateway

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-dotnet
spec:
  selector:
    app: frontend
    language: dotnet
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
