services:
  collector:
    extends:
      file: ../docker-compose.yml
      service: collector

  year:
    build: year
    environment:
      - OTEL_COLLECTOR_HOST=collector
    ports:
      - "6001:6001"

  frontend:
    build: frontend
    environment:
      - NAME_ENDPOINT=name:8000
      - MESSAGE_ENDPOINT=message:9000
      - OTEL_COLLECTOR_HOST=collector
    ports:
      - "7007:7007"

  name:
    build: name
    environment:
      - YEAR_ENDPOINT=year:6001
      - OTEL_COLLECTOR_HOST=collector
    ports:
      - "8000:8000"

  message:
    build: message
    environment:
      - OTEL_COLLECTOR_HOST=collector
    ports:
      - "9000:9000"
