apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-python
  labels:
    app: message
    language: python
spec:
  selector:
    matchLabels:
      app: message
      language: python
  template:
    metadata:
      labels:
        app: message
        language: python
    spec:
      containers:
      - name: message-python
        image: hnyexample/message-python
        ports:
        - containerPort: 9000
        env:
        - name: HONEYCOMB_API_KEY
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: api_key
        - name: HONEYCOMB_DATASET
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: dataset
        - name: SERVICE_NAME
          value: message-python

---
apiVersion: v1
kind: Service
metadata:
  name: message-python
spec:
  selector:
    app: message
    language: python
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
