apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-dotnet
  labels:
    app: message
    language: dotnet
spec:
  selector:
    matchLabels:
      app: message
      language: dotnet
  template:
    metadata:
      labels:
        app: message
        language: dotnet
    spec:
      containers:
      - name: message-dotnet
        image: hnyexample/message-dotnet
        ports:
        - containerPort: 9000
        env:
        - name: Otlp__Endpoint
          value: "http://collector:55680"

---
apiVersion: v1
kind: Service
metadata:
  name: message-dotnet
spec:
  selector:
    app: message
    language: dotnet
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
