apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-java
  labels:
    app: message
    language: java
spec:
  selector:
    matchLabels:
      app: message
      language: java
  template:
    metadata:
      labels:
        app: message
        language: java
    spec:
      containers:
      - name: message-java
        image: hnyexample/message-java
        ports:
        - containerPort: 9000
        env:
        - name: HONEYCOMB_API_KEY
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: api_key
        - name: HONEYCOMB_DATASET
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: dataset
        - name: SERVICE_NAME
          value: message-java
        - name: OTEL_METRICS_EXPORTER
          value: none

---
apiVersion: v1
kind: Service
metadata:
  name: message-java
spec:
  selector:
    app: message
    language: java
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
