services:
  frontend:
    build: frontend
    environment:
      - HONEYCOMB_API
      - HONEYCOMB_API_KEY
      - HONEYCOMB_DATASET
      - NAME_ENDPOINT=name:8000
      - MESSAGE_ENDPOINT=message:9000
      - SERVICE_NAME=node-frontend-service
    ports:
      - 7000:7000

  message:
    build: message-service
    environment:
      - HONEYCOMB_API
      - HONEYCOMB_API_KEY
      - HONEYCOMB_DATASET
      - SERVICE_NAME=node-message-service
    ports:
      - 9000:9000

  name:
    build: name-service
    environment:
      - HONEYCOMB_API
      - HONEYCOMB_API_KEY
      - HONEYCOMB_DATASET
      - SERVICE_NAME=node-name-service
      - YEAR_ENDPOINT=year:6001
    ports:
      - 8000:8000

  year:
    build: year-service
    environment:
      - HONEYCOMB_API_KEY
      - HONEYCOMB_DATASET
      - OTLP_ENDPOINT
      - SERVICE_NAME=node-year-service
    ports:
      - 6001:6001
