services:
  frontend:
    build: frontend
    environment:
      - HONEYCOMB_API
      - HONEYCOMB_API_KEY
      - HONEYCOMB_DATASET
      - MESSAGE_ENDPOINT=message:9000
      - SERVICE_NAME=node-frontend-service
    ports:
      - 7000:7000

  message:
    build: message-service
    environment:
      - HONEYCOMB_API
      - HONEYCOMB_API_KEY
      - HONEYCOMB_DATASET
      - SERVICE_NAME=node-message-service
    ports:
      - 9000:9000

  year:
    build: year-service
    environment:
      - HONEYCOMB_API_KEY
      - HONEYCOMB_DATASET
      - OTLP_ENDPOINT
      - SERVICE_NAME=node-year-service
    ports:
      - 6001:6001
