version: "2.4"

x-common-env: &common-env
  HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
  OTEL_EXPORTER_OTLP_ENDPOINT: https://api.honeycomb.io
  HONEYCOMB_API_ENDPOINT: https://api.honeycomb.io
  OTEL_RESOURCE_ATTRIBUTES: app.running-in=docker
  MESSAGE_ENDPOINT: http://message:9000
  NAME_ENDPOINT: http://name:8000
  YEAR_ENDPOINT: http://year:6001

services:
  frontend:
    build: frontend
    image: hnyexample/frontend-python
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: frontend-python
    ports:
      - 7777:7777

  message:
    build: message-service
    image: hnyexample/message-python
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: message-python
    ports:
      - 9000:9000

  name:
    build: name-service
    image: hnyexample/name-python
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: name-python
    ports:
      - 8000:8000

  year:
    build: year-service
    image: hnyexample/year-python
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: year-python
    ports:
      - 6001:6001

