apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-dotnet
  labels:
    app: name
    language: dotnet
spec:
  selector:
    matchLabels:
      app: name
      language: dotnet
  template:
    metadata:
      labels:
        app: name
        language: dotnet
    spec:
      containers:
      - name: name-dotnet
        image: hnyexample/name-dotnet
        ports:
        - containerPort: 8000
        env:
        - name: Otlp__Endpoint
          value: "http://collector:55680"
        - name: YEAR_ENDPOINT
          value: http://gateway

---
apiVersion: v1
kind: Service
metadata:
  name: name-dotnet
spec:
  selector:
    app: name
    language: dotnet
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
