apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-java
  labels:
    app: name
    language: java
spec:
  selector:
    matchLabels:
      app: name
      language: java
  template:
    metadata:
      labels:
        app: name
        language: java
    spec:
      containers:
      - name: name-java
        image: hnyexample/name-java
        ports:
        - containerPort: 8000
        env:
        - name: HONEYCOMB_API_KEY
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: api_key
        - name: HONEYCOMB_DATASET
          valueFrom:
            configMapKeyRef:
              name: hny-config
              key: dataset
        - name: SERVICE_NAME
          value: name-java
        - name: YEAR_ENDPOINT
          value: http://year
