##################################################################################################
# name-go services
##################################################################################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: name-go
  namespace: greetings
---
apiVersion: v1
kind: Service
metadata:
  name: name
  namespace: greetings
  labels:
    app: name
    service: name
    app.kubernetes.io/name: name-go
spec:
  selector:
    app: name
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-go
  namespace: greetings
  labels:
    app: name-go
    app.kubernetes.io/name: name-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name
  template:
    metadata:
      labels:
        app: name
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: /app/name-service
    spec:
      serviceAccountName: name-go
      terminationGracePeriodSeconds: 0
      containers:
        - name: name
          image: name-go-auto:local
          ports:
          - containerPort: 8000
            name: http
          env:
          - name: YEAR_ENDPOINT
            value: http://year:6001
