name: Publish to GHCR

on: [workflow_dispatch,push]

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [frontend, message, year, name]
    steps:
      - uses: actions/checkout@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: |
            ghcr.io/${{ github.repository }}/egs-${{ matrix.service }}-go

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          file: go-uninstrumented/${{ matrix.service }}-service.Dockerfile
          push: true
          tags: dev
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
